### ISSUE TITLE
Python 3.8

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-api#577]
According to my local tests, Python 3.8 just works as expected.

Nevertheless, we should update the following for official support:
- [x] Readme & Manual #581
- [x] update version ranges & tags in `setup.py` #581
- [x] `manylinux2010` builds in `Dockerfile` #615
  - [x] waiting for [upstream](https://github.com/pypa/manylinux/commit/885a71320e3bc775eec581a0112388c583224da5)
  - [x] clarify change in abi tag `cp37m` to `cp38`: https://github.com/pypa/manylinux/issues/393
- [ ] add to CI: Linux (#581), OSX(...), Windows (...)
- [x] add to conda-forge [feedstock](https://github.com/conda-forge/openpmd-api-feedstock/): https://github.com/conda-forge/openpmd-api-feedstock/pull/35
  - [x] waiting for upstream
- [ ] potentially bump pybind11 to [2.4.1+](https://github.com/pybind/pybind11/search?q=3.8&unscoped_q=3.8) or [later](https://github.com/pybind/pybind11/pull/1974)

Nothing to do in:
- [x] `CMakeLists.txt`
- [x] Spack package
