### ISSUE TITLE
ADIOS2: New Layout in openPMD 2

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-api#920]
This is a meta-issue to document new layout options in ADIOS2.

Related to https://github.com/openPMD/openPMD-standard/issues/221

- [x] mutable attributes: Use ADIOS variables for openPMD attributes #813
- [ ] `OPENPMD_NEW_ATTRIBUTE_LAYOUT`: generalize control variable to "openPMD2_adios2_schema" ("new_layout")?
- [ ] store the YYYYMMDD as attribute of the new layout so we can identify it if we need to in reads. just bump during dev whenever we change things
- [ ] variable encoding: add a `__steps__` variable in base path #855
- [ ] decide on bool support for variables: #921
